import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
const nebularRegualr = localfont({
  src: "./fonts/Nebula-Regular.otf",
  variable: "--font-nebular",
});

const nebularHollow = localfont({
  src: "./fonts/Nebula-Hollow.otf",
  variable: "--font-nebular-hollow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nebularRegualr.variable} ${nebularHollow.variable} ${poppins.variable} ${roboto.variable} antialiased`}
      >
        <Toaster />
        <Header />
        {children}
      </body>
    </html>
  );
}
